= Clean Up Fair Sharing
:navtitle: Clean Up

Clean up all fair sharing resources and revert to classical preemption.

== References

* https://kueue.sigs.k8s.io/docs/concepts/cluster_queue/#fair-sharing[Kueue: Fair Sharing^]
* https://kueue.sigs.k8s.io/docs/concepts/cluster_queue/#preemption[Kueue: Preemption^]
* https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html-single/ai_workloads/index#configuring-fairsharing[Red Hat build of Kueue: Configuring Fair Sharing^]

== Lab: Clean Up

=== 1. Clean up fair sharing

NOTE: The xref:admission-fair-sharing.adoc#cleanup-admission-fs[Clean up admission fair sharing] step already cleaned up the admission fair sharing resources (`shared-gpu-queue`, `research-queue`, `production-queue`) and scaled the operator back up.
This step cleans up the DRS fair sharing resources from the DRS fair sharing exercises and reverts the Kueue CR to classical preemption.

Delete all remaining workloads and DRS fair sharing resources:

[source,console,subs="+quotes"]
----
$ **oc delete jobs --all -n training-jobs**
job.batch "team-a-job-1" deleted
job.batch "team-a-job-2" deleted
job.batch "team-a-job-3" deleted

$ **oc delete jobs --all -n team-b-jobs**
job.batch "team-b-job-1" deleted
job.batch "team-b-job-2" deleted

$ **oc delete localqueue team-a-queue -n training-jobs**
localqueue.kueue.x-k8s.io "team-a-queue" deleted

$ **oc delete localqueue team-b-queue -n team-b-jobs**
localqueue.kueue.x-k8s.io "team-b-queue" deleted

$ **oc delete clusterqueue team-a-cluster-queue team-b-cluster-queue**
clusterqueue.kueue.x-k8s.io "team-a-cluster-queue" deleted
clusterqueue.kueue.x-k8s.io "team-b-cluster-queue" deleted

$ **oc delete namespace team-b-jobs**
namespace "team-b-jobs" deleted
----

Revert the Kueue CR to classical preemption:

[source,console,subs="+quotes"]
----
$ **oc patch kueues.kueue.openshift.io cluster -n openshift-kueue-operator --type merge -p '{**
  **"spec": {**
    **"config": {**
      **"preemption": {**
        **"preemptionPolicy": "Classical"**
      **}**
    **}**
  **}**
**}'**
kueue.kueue.openshift.io/cluster patched
----

Wait about 15 seconds for the operator to reconcile, then restore the original isolated ClusterQueues:

[source,console,subs="+quotes"]
----
$ **oc apply -f kueue-config/3-cluster-queues.yaml**
clusterqueue.kueue.x-k8s.io/a100-cluster-queue unchanged
clusterqueue.kueue.x-k8s.io/t4-cluster-queue unchanged
----

Verify clean state:

[source,console,subs="+quotes"]
----
$ **oc get clusterqueues**
NAME                 COHORT   PENDING WORKLOADS
a100-cluster-queue            0
default                       0
t4-cluster-queue              0

$ **oc get pods -n openshift-kueue-operator --no-headers**
kueue-controller-manager-6c6dd585cc-7mhtw   1/1   Running   0     28s
kueue-controller-manager-6c6dd585cc-gt96l   1/1   Running   0     27s
openshift-kueue-operator-5b4c49c95c-9mql2   1/1   Running   0     5m6s
openshift-kueue-operator-5b4c49c95c-m469q   1/1   Running   0     5m6s

$ **oc get kueues.kueue.openshift.io cluster -n openshift-kueue-operator** \
  **-o jsonpath='{.spec.config.preemption}' | python3 -m json.tool**
{
    "preemptionPolicy": "Classical"
}
----

== Summary

You have demonstrated two types of fair sharing:

* *DRS Fair Sharing* (DRS fair sharing exercises) -- proportional preemption between ClusterQueues in a cohort, driven by `weightedShare` (DRS) scores and `fairSharing.weight` values
* *Admission Fair Sharing* (admission fair sharing exercise) -- usage-based admission ordering within a single ClusterQueue, driven by historical `consumedResources` per LocalQueue

== Fair Sharing Configuration Summary

[cols="2,3,1", options="header"]
|===
|File |Resources |Scope

|`10-fair-sharing.yaml`
|Namespace `team-b-jobs`, 2 ClusterQueues with `fairSharing.weight`, 2 LocalQueues in `fair-sharing-cohort`
|Cluster

|`job-fair-sharing-team-a.yaml`
|3 Team A jobs (1 GPU each) in `training-jobs`
|Namespace

|`job-fair-sharing-team-b.yaml`
|2 Team B jobs (1 GPU each) in `team-b-jobs`
|Namespace

|`10a-admission-fair-sharing.yaml`
|1 ClusterQueue with `admissionScope`, 2 LocalQueues (`research-queue`, `production-queue`)
|Cluster

|`job-admission-fs-round1.yaml`
|2 Research jobs (1 GPU each) in `training-jobs`
|Namespace

|`job-admission-fs-round2.yaml`
|2 Research + 2 Production jobs (1 GPU each) in `training-jobs`
|Namespace
|===

In the xref:mig:index.adoc[next chapter], you learn how to partition A100 GPUs into MIG instances and manage them with Kueue.

TIP: For a complete cluster reset (removing ALL lab resources), see xref:cluster-reset:index.adoc[Cluster Reset].
